# plugins:
discourse-download-limiter:
  discourse_download_limiter_enabled:
    default: false
    client: true
  download_allowed_group:
    default: "1|2"
    type: group_list
    description: "Sets the user group whose members are allowed to download file attachments."
